<h1><center>  Lab 1 : Introduction to Python </center>
<img src="https://files.realpython.com/media/Newbie_Watermarked.a9319218252a.jpg" width="400">

> `Created by: Jinnie Shin (jinnie.shin@ualberta.ca)`\
> `Date: 18 May 2023 (Summer A 2023)`
---

## 1. Basic Data Type in Python <a class="anchor" id="data"></a>

|  Object Type |              Example              |           Shortcut         |
|:------------|:---------------------------------|:------------------:|
| Numbers      | 123, 3.14, 3+4j, 1000             | ```int(a)``` or ```float(a)``` |
| String       | "student", "class", "fun"         | ```string(a)``` or ```" "```   |
| Lists        | [1,2,3], ["student", "fun"]       | ```list(a)``` or ```[a]```     |
| Dictionaries | {'Jane':'high', 'Matt':'average'} | ```dict(a)``` or ```{a:b}```   |
| Tuples       | ('Jane', 'high'), (1, 2)          | ```tuple(a)``` or ```(a,b)```  |
| Sets         | set('abc') {a, b, c}              | ```set(abc)``` or ```{a,b,c}```         |
| Booleans     | True or False                     | ```a==b``` or``` a!=b```       |

In [4]:
# integers
print(type(10))
# float 
print(type(1.82))
# string
print(type('Hello everyone'))
# boolean
print(type(2==1))
print(type(False))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>
<class 'bool'>


In [1]:
# before we run the code, let's guess what will happen

# Comments

str(2.2)
float(2.2)
str(2.2)
bool(2.2) == True

print(type(1.28), type("hello"), type("300"))

type("300") == type("hey")

<class 'float'> <class 'str'> <class 'str'>


True


---
### 1.1. List <a class="anchor" id="list"></a>

> A ```[list]``` can be create in multiple ways by placing elements inside a square bracket ```[list]```



In [7]:
list1 = [] # empty list
list2 = [1,2,3,4] # integer elements 
list3 = ['hello', 'my', 'name', 'is', 'jinnie'] #string elements
list4 = list(range(1,4)) # list using a range 1~3
list4
list5 = list(range(10,21))
list5

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

> Lists can be nested within each other as a nested list ```[[nested_list],[list]]```

In [10]:
nested_list =[list3, list2, list5]
nested_list

[['hello', 'my', 'name', 'is', 'jinnie'],
 [1, 2, 3, 4],
 [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]]

> Dimension of the list can be identified by chekcing the length of the list ```len(list(a))```

In [18]:
len(nested_list)

len(list3)

## Get the final element of nested_list

## len starts with position 0, so element 3 is index [2]
len(nested_list[2])

## or to get final element use -1, as it counts backwards
##  -2 would be second from last
len(nested_list[-1])

11

> List elements can be accessed by indexing ```list[index]```

In [ ]:
list2[0] # element indices start from 0 
nested_list[0]

[]

In [21]:
list3[-1] #final element can be accessed by negative indexing 
list3[0:2] # a range could be provided to call multiple elements
                # Note this works like range() command, so final will be -1-ed
                # Make sure 
list3[:-2] # except the last two elements
list3[4:] # starting from the 4th element
list3[:] # all the elements 

['hello', 'my', 'name', 'is', 'jinnie']

> We can add, remove, or replace the elements using ```list.extend()```, ```list.append()```, ```list.remove()```, ```list.clear()```

In [34]:
list3[0] = 'Byeeee' # change the first element of list3 to 'Bye'
print('revised list is ' + str(list3))

list3[-1] = "Matt"
print('revised list is ' + str(list3))

revised list is ['Byeeee', 'my', 'name', 'is', 'Matt', 5, 6, 7, 8, 9, 10]
revised list is ['Byeeee', 'my', 'name', 'is', 'Matt', 5, 6, 7, 8, 9, 'Matt']


In [35]:
new_list = [5,6,7,8,9]
complete_list1 = list3.extend(new_list) # extend the original list with a new list 
print(complete_list1)

None


In [36]:
complete_list2 = list3.append(10) # append a new element
print(complete_list2)

None


In [38]:
new_list.remove(5) # remove an element from the list 
print(new_list)

ValueError: list.remove(x): x not in list

In [37]:
new_list.clear() # clear the list 
print(new_list)

[]


### 1.2. Matrix <a class="anchor" id="matrix"></a>

> Python does not have a built-in type for matrices. Instead, we can treat list of a list as a matrix ```[[list], [list]]```

In [39]:
matrix = [[1,2,3,4],
          [5,6,7,8]]
matrix

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [47]:
# Use ! to push the line to terminal
!pip install numpy 
# conda install numpy
# import numpy as np # import numpy functions as np 

> We will import ```numpy``` to do simple matrix calculations

In [1]:
import numpy as np

In [3]:
A = np.array([[1,2,3,4], [5,6,7,8]]) #np.array to create a matrix
print(A)
B = np.array([[0,1],[2,3],[4,5],[7,8]])
print(B)
A.shape # check dimensions 

[[1 2 3 4]
 [5 6 7 8]]
[[0 1]
 [2 3]
 [4 5]
 [7 8]]


(2, 4)

In [16]:
# Creates 2 x 3 matrix of all zeros, can be useful to set up a container for other data
Z = np.zeros([2,3])
# Creates 2 x 3 matrix random numbers, might be random weights you experiement with
# Within range 0 to 1 by default
R = np.random.rand(2,3)
# Creates 2 x 3 matrix random intergers with range 0 - 1 (becasue range() is 2-1)
I = np.random.randint(2, size=(2, 3))
I

array([[1, 1, 0],
       [0, 0, 0]])

>   We can use ```np.maxtrix()``` to create a matrix

In [20]:
# Numpy matrix uses spaces to sep values and semi-colons to sep columns
aa = np.matrix('1 2 3 ; 4 5 6')
aa

D = np.random.randint(3, size = (3,3))

> We can access elements just like we did with a list using ```matrix[index][index]```

In [22]:
# print(D)
print(D[0]) # first row 
print(D[0][0]) #first row, first element (0,0)

[1 2 0]
1


> We can compute a matrix transpose using ```matrix.transpose()```

In [24]:
# Flips the matrix
DT = D.transpose()
DT

array([[1, 2, 0],
       [2, 0, 1],
       [0, 1, 1]])

> We can create a dot product using ```matrix.dot()```

In [26]:
# Multiply the matrix by each other
DxDT = D.dot(DT)
DxDT

array([[5, 2, 2],
       [2, 5, 1],
       [2, 1, 2]])

> We can compute the Euclidean distance between the two vectors (or lists) using ```np.linalg.norm```

In [ ]:
E = np.array([[-7,-3,-2,1],[1,3,6,9]])
# Euclidean distance
dist = np.linalg.norm(A-E)
dist

<img src="https://i.pinimg.com/736x/2e/aa/7d/2eaa7d5021ca7c3c98bc93b98b9646fe.jpg" align="left" width="70" height="70" align="left">

> ### Task 1 - Create multiple matrices from a list
> - *Q1*: Create a 4 by 4 matrix from the list and call it M1 - HINT (```.reshape```)
> - *Q2*: Get the (1) tanspose (```matrix.transpose()```) and (2) inverse of the matrix M1
> - *Q3*: Get the dot product of (1) M1 and its transpose and (2) M1 and its inverse



In [30]:
lst = np.random.rand(16)
lst
############################# Your code Here ############################################

# Q1: Create a 4 by 4 matrix from the list and call it M1 - HINT (.reshape)
M1 = np.matrix(lst)
M1

M2 = np.reshape(M1, newshape = [4,4])
M2
##########################################################################################

matrix([[0.28322858, 0.73237643, 0.28917624, 0.63743382],
        [0.86533831, 0.80069317, 0.03126777, 0.36922641],
        [0.16201467, 0.59873606, 0.3427353 , 0.75680401],
        [0.8415933 , 0.07515508, 0.62439638, 0.15258954]])

In [39]:
############################# Your code Here ############################################
# Q2: Get the (1) tanspose and (2) inverse of the matrix M1

M3 = np.matrix.transpose(M2)

M5 = np.linalg.inv(M2)

##########################################################################################

In [40]:
############################### Your code Here ###########################################
# Q3: Get the dot product of (1) M1 and its transpose and (2) M1 and its inverse

M4 = M2.dot(M3)
M6 = M2.dot(M5)



##########################################################################################

### 1.3. Dictionary <a class="anchor" id="dict"></a>
> Python dictionaries ```{ }``` store keys: values to easily access values that are mapped together ```dict[key] = value```

In [42]:
# Need to create a blank dictionary first
Dict = {}

In [44]:
# Now you can add keys (names) and values (birthdays) to slots in the blank Dict
Dict['Connie'] = '1990-06-18' # add elements using [keys] = values 
Dict['Cora'] = '1994-07-17'
Dict['Hunter'] = '1998-01-01'
Dict['James'] = '1970-08-15'
Dict['Sophie'] = '2001-02-14'

print(Dict)

{'Connie': '1990-06-18', 'Cora': '1994-07-17', 'Hunter': '1998-01-01', 'James': '1970-08-15', 'Sophie': '2001-02-14'}


> You can define all the keys/values when creating a dictionary as well ```{key:value}```

In [45]:
new_dict = {'Cora': '1994-07-17',
            'Hunter': '1998-01-01',
            'James': '1970-08-15',
            'Sophie': '2001-02-14',
            'Connie': '1990-06-18'}

# Checks they are the same as each other
new_dict == Dict

True

> You can easily accessing information with the dictionary keys

In [46]:
# Now we want to get Connie's birthday
Dict['Connie']

'1990-06-18'

> You can extract the keys and values using ``` {dict}.keys()``` and ```{dict}.values()```

In [47]:
Dict.keys()
Dict.values()

dict_values(['1990-06-18', '1994-07-17', '1998-01-01', '1970-08-15', '2001-02-14'])

In [48]:
names = list(Dict.keys())
bdays = list(Dict.values())
names

['Connie', 'Cora', 'Hunter', 'James', 'Sophie']

<img src="https://i.pinimg.com/736x/2e/aa/7d/2eaa7d5021ca7c3c98bc93b98b9646fe.jpg" align="left" width="70" height="70" align="left">


> ### Task 2 - Create a new dictionary 
> - *Q1*: Create a new dictionary that stores birthdays as keys and names as vlalues and call it ```re_dict```
> - *Q2*: Remove month-date from the keys and call it ```new_dict```

In [50]:
################################ Your code Here #########################################
# Hint zip()

# Zips two lists together than are the same length
re_dict = zip(names, bdays)

# expected outcome:
#{'Connie': '1990-06-18',
# 'Cora': '1994-07-17',
# 'Hunter': '1998-01-01',
# 'James': '1970-08-15',
# 'Sophie': '2001-02-14'}
##########################################################################################

In [61]:
################################## Your code Here #######################################
#Hint  str.split('')

# This is how it works
"1990-06-18".split(sep = "-")

# Make empty list for years
years = []

# For loop
for i in bdays:
    temp = i.split(sep = "-")
    year = temp[0] # This will be the year as its the first index of the split list
    years.append(year) # This will add each year to the 

print(years)

new_dict = zip(names, years)
print(new_dict)

# expected outcome
#{'1970': 'James',
# '1993': 'Jinnie',
# '1994': 'Cora',
# '1998': 'Hunter',
# '2001': 'Sophie'}
#########################################################################################

['1990', '1994', '1998', '1970', '2001']


<img src="https://i.pinimg.com/736x/2e/aa/7d/2eaa7d5021ca7c3c98bc93b98b9646fe.jpg" align="left" width="70" height="70" align="left">


> ### Task 3 - Apply a function to the dictionary 
> - *Q1*: what is the average quiz scores of jinnie, erin, and mark, respectively?
> - *Q2*: In which quiz, did jinnie, eric and mark achieve the highest score, respectively?


In [91]:
# Nested dictionary with quiz dictionary having multiple values
result = {'jinnie': {'quiz': [90.0,97.0,75.0,92.0]},
          'erin':{'quiz' : [ 100.0, 92.0, 93.0, 67.0]},
          'mark':{'quiz': [100.0, 91.0, 89.0, 97.0]}
}


# what is the average quiz scores of jinnie, erin, and mark, respectively?

####################### Your code here #####################

result['jinnie'] # we know that this function will take an input eg. {'quiz': [90.0, 97.0, 75.0, 92.0]}
result['jinnie']['quiz'] # now we have a list that only saves the quiz score
print(np.min(result["erin"]["quiz"])) 

## Define a function called mean_score()
    ## Taking inputs input_dic
def mean_score(input_dic): 
        ## Take a the quiz from the input input_dic and save it in temp
    temp = input_dic['quiz'] #this will output a list = []
    
    # numpy average is the mean
    return np.average(temp)


###########################################################
score = mean_score(result['mark']) # Use the above defined function
print(score)

print("How about Erin's score?")
mean_score(result['erin'])

67.0
94.25
How about Erin's score?


88.0

In [96]:
# In which quiz, did jinnie, erin and mark achieve the highest score, respectively?

####################### Your code here ######################

# New function to return where students scored the highest
def where_highest(input_dic):
    temp = input_dic['quiz'] #this will output a list = [] 

    return print('Highest score in quiz ', np.argmax(temp)+1)

############################################################

where_highest(result['jinnie'])

## Create a function that identifies when each person scores the lowest
def where_lowest(input_dic):
    temp = input_dic['quiz'] #this will output a list = [] 

    return print('Lowest score in quiz ', np.argmin(temp)+1)

where_lowest(result['erin'])
where_lowest(result['jinnie'])
where_lowest(result['mark'])

Highest score in quiz  2
Lowest score in quiz  4
Lowest score in quiz  3
Lowest score in quiz  3


### 1.4. String <a class="anchor" id="string"></a>
> There are number of built-in string objects to implememnt higher-level operations with strings (e.g., parsing, joinining) 

|      Method  Type      |                                                                    Description                                                                    |
|:----------------------|:-------------------------------------------------------------------------------------------------------------------------------------------------|
| ```S.capitalize()```         | returns a string with the first character in the capital                                                                                          |
| ```S.upper()```  ```S.lower()``` | ```.upper()``` method on a string converts all of the characters to uppercase,  whereas the ```.lower()``` method converts all of the characters to lowercase |
| ```S.casefold()```           | removes all case distinctions present in a string                                                                                                 |
| ```S.encode()```             | returns encoded version of the given string                                                                                                       |
| ```S.find()```               | returns the index of first occurrence of the substring (if found). If not found, it returns -1.                                                   |
| ```S.index()```              | returns the index of a substring inside the string (if found). If the substring is not found, it raises an exception.                             |
| ```S.isalpha() ```           | returns True if all characters in the string are alphabets. If not, it returns False.                                                             |
| ```S.isdigit()```            | returns True if all characters in a string are digits. If not, it returns False.                                                                  |
| ```S.replace() ```           | returns a copy of the string in which the occurrences of old have been replaced with new value                                                    |
|``` S.split() ```             | split a string into a list where each word is a list item.returns a copy of the string by removing the trailing characters specified as argument  |
| ```S.rstrip()```             | returns a copy of the string by removing the trailing characters specified as argument                                                            |

In [68]:
## Let's explore!
S = "WE CAN TRY ALL OF THIS FUNCTIONS!"

S.lower().capitalize()

'We can try all of this functions!'

> Individual elements in string can be accessed as in lists.

In [69]:
string ='here is another example. more than 100 examples will be provided in this class.'
string[0] # can you guess the output?
string[-1] # can you guess the output?

'.'

<img src="https://i.pinimg.com/736x/2e/aa/7d/2eaa7d5021ca7c3c98bc93b98b9646fe.jpg" align="left" width="70" height="70" align="left">


### Task 4 - String Methods
> - *Q1*: Replace the word "examples" to "pratice questions" in the given string.  (S.replace())
> - *Q2*: Capitalize the first letters in each sentence. (S.capitalize())
> - *Q3*: Identify the index of the first time the alphabet 'i' appears in the given string. (S.find())


In [112]:
####################### Your code here ######################
# Q1. replace the word "examples" to "pratice questions" in the given string using S.replace()
string = "Matt has the examples"

string.replace('examples', 'practice questions')

string.lower()
string.upper()
string.capitalize()
string.split("has")

# Replace spaces with nothing
string.replace(" ", "")
string.replace(" ", "_")

############################################################

'Matt_has_the_examples'

In [118]:
####################### Your code here ######################
# Q2. Identify the total number of unique alphbets in the given string. (S.isaplha())
string = "Hi there. How are you?"

print(string.split(' ')[1])

# Split the string by period and space
new_string = string.split('. ')
new_string

first_sentence = new_string[0]
print(first_sentence)
second_sentence= new_string[-1] # or you can do [1]
print(second_sentence)

# Set gets the letters used in creating the string
first_sentence_letters = set(first_sentence)
print(first_sentence_letters)

second_sentence_letters = set(second_sentence)
second_sentence_letters
############################################################

there.
Hi there
How are you?
{' ', 't', 'r', 'i', 'H', 'h', 'e'}


{' ', '?', 'H', 'a', 'e', 'o', 'r', 'u', 'w', 'y'}

In [72]:
####################### Your code here ######################
# Q3. Identify the index of the first time the alphabet 'i' appears in the given string. (S.find())
string.find('i')
string[5] # this is actually the 6th element because of the weird range thing
############################################################

'i'

## 2. Basic Python Statement <a class="anchor" id="statement"></a>

> There are *three* types of loops and statements in Python, For loops, While loops, and if-else statements. 
>>```For loops```: Iterates over a sequence of elements in a list or a range.\
>>```While loops```: Repeat as long as a certain boolean condition satisfies.\
>>```If-else statement```: conditional statements that provide you with the decision making that is required when you want to execute code based on a particular condition.

### 2.1. For Loops <a class="anchor" id="for"></a>
    > for i in list: 
        {action}
      

In [122]:
list2 =[ 1,2,3,4] # we will work with this list

for prime in list2:
  print(prime)

for i in list2:
  print(i + 1)

list3 = []
for i in list2:
  temp = i+10
  list3.append(temp)
  print(list3)

1
2
3
4
2
3
4
5
[11]
[11, 12]
[11, 12, 13]
[11, 12, 13, 14]


In [123]:
for prime in range(1,5): # range(1,5) = [1,5) 1, 2, 3, 4 
  # % is remainder after divide, so this is checking if even number
  if (prime % 2) == 0: # % modulus # if this is true  # this is why the definition concerned "boolean"
    print(prime)
  else:
    print('odd number')
    


odd number
2
odd number
4


> We can also write a for loop in one line ```[print(i) for i in list]```

In [75]:
for prime in list2:
    print(prime)


## Alternate way of writing functions, it's the same thing but backwards    
[print(prime) for prime in list2]

1
2
3
4
1
2
3
4


[None, None, None, None]

### 2.2. While Loops <a class="anchor" id="while"></a>
    > while i == {Condition}: 
        {action}

In [76]:
# print 0,1,2,3,4
count = 0
while count < 10: 
  print(count)
  count += 1 # this equals to count = count + 1 (shorthand)
    

0
1
2
3
4
5
6
7
8
9


> You can also ```break``` or ```continue``` the while loop 

In [77]:
count = 0
while True:
  print(count)
  count +=1
  if count >= 5:
    break 

# Prints out only odd numbers - 1,3,5,7,9
for x in range(10):
    # Check if x is even
    if x % 2 == 0:
        continue
    print(x)


0
1
2
3
4
1
3
5
7
9


> A simple element-wise operation with ```zip()``` or ```for-loop```

In [124]:
odd_list = [1, 3, 5, 7, 9]
even_list = [2, 4, 6, 8, 10]

In [125]:
add = odd_list + even_list # Just appends the lists, does't interlock them
print('element-wise addition: ' + str(add))

element-wise addition: [1, 3, 5, 7, 9, 2, 4, 6, 8, 10]


In [127]:
add = [odd-even for odd, even in zip(odd_list, even_list)]
print('element-wise addition using zip(): ' + str(add))


## Making a loop with two elements i and j and two lists odd_list and even_list
for i, j in zip(odd_list, even_list):
    print(i + j)


element-wise addition using zip(): [-1, -1, -1, -1, -1]
3
7
11
15
19


In [81]:
add = [odd_list[i]*even_list[i] for i in range(len(odd_list))]
print('element-wise addition using a loop: ' + str(add))

element-wise addition using a loop: [2, 12, 30, 56, 90]


### 2.3. If/elif/else statement <a class="anchor" id="if"></a>
    > if {Condition1}:
        {action}
      elif {Condition2}:
        {action}
      else:
        {action}
      

In [82]:
## elif is equivilant to else if{} in R

for i in odd_list: 
    if i <2:
        print('value too small')
    elif i==3:
        print('value appropriate')
    else:
        print(i)
    

value too small
value appropriate
5
7
9


<img src="https://i.pinimg.com/736x/2e/aa/7d/2eaa7d5021ca7c3c98bc93b98b9646fe.jpg" align="left" width="70" height="70" align="left">


### Task 5 - Simple Calculation using for loops 
> - *Q1*: Conduct a element-wise subtraction ```even_list``` - ```odd_list```
> - *Q2*: Translate character of alphabet into a simple number decipher! (HINT: ```chr()``` returns character from the number e.g. ```chr(65) ='A'```) 
> - *Q3*: defining a function called ```def encode``` that encodes a string into a list of number or digits



In [129]:
######################## Your Code Here ###########################
#Q1 ANSWER 

even_list = [2,4,6,8,10]
odd_list = [1,3,5,7,9]

sub = [even - odd for (even, odd) in zip(even_list, odd_list)] 
print(sub)


###################################################################

[1, 1, 1, 1, 1]


In [139]:
encoded = [73, 32, 107, 110, 111, 119, 32, 105, 116, 32, 105, 115, 32, 
           104, 97, 114, 100, 32, 116, 111, 32, 99, 111, 109, 101, 32,
           104, 101, 114, 101, 32, 101, 118, 101, 114, 121, 32, 
           115, 97, 116, 117, 114, 100, 97, 121, 46]

def decode(encoded): # defining a function called "decode"
    final = [] 
    ####### your code here ###############
    #Q2 ANSWER 
    for i in encoded:
        temp = chr(i)
        #print(temp)
        final.append(temp)
    
    
    #######################################
    return final 

output = decode(encoded)
print(' '.join(output))

I   k n o w   i t   i s   h a r d   t o   c o m e   h e r e   e v e r y   s a t u r d a y .


In [143]:
"A".encode()

b'A'

In [159]:
sentence = 'Are you planning to travel this summer?'

def encode(sentence): # defining a function called "encode"
    final = [] 
    ####### your code here ###############
    #Q3 ANSWER 
    for i in sentence:
        temp = i.encode()
        final.append(temp)
    #######################################
    return final 

encode(sentence)
#output = encode(sentence)

[b'A',
 b'r',
 b'e',
 b' ',
 b'y',
 b'o',
 b'u',
 b' ',
 b'p',
 b'l',
 b'a',
 b'n',
 b'n',
 b'i',
 b'n',
 b'g',
 b' ',
 b't',
 b'o',
 b' ',
 b't',
 b'r',
 b'a',
 b'v',
 b'e',
 b'l',
 b' ',
 b't',
 b'h',
 b'i',
 b's',
 b' ',
 b's',
 b'u',
 b'm',
 b'm',
 b'e',
 b'r',
 b'?']

# Important Package - Pandas 

In [ ]:
!pip install pandas 

In [ ]:
import pandas as pd

# Create a DataFrame
data = {
    'Name': ['John', 'Emily', 'Ryan', 'Linda', 'Michael'],
    'Age': [25, 30, 35, 28, 32],
    'City': ['New York', 'Chicago', 'San Francisco', 'Los Angeles', 'Boston']
}

df = pd.DataFrame(data)

# Display the DataFrame
print("Original DataFrame:")
print(df)
print()


In [ ]:
# Accessing data
print("Accessing data:")
print("Name column:")
print(df['Name'])
print()

print("First row:")
print(df.loc[0])
print()


In [ ]:
# Filtering data
print("Filtering data:")
filtered_df = df[df['Age'] > 30]
print("People above 30 years old:")
print(filtered_df)
print()

# Adding a new column
df['Salary'] = [50000, 60000, 70000, 55000, 65000]
print("DataFrame with a new column:")
print(df)
print()


In [ ]:
# Aggregating data
print("Aggregating data:")
average_age = df['Age'].mean()
print("Average age:", average_age)
print()

# Sorting data
print("Sorting data:")
sorted_df = df.sort_values(by='Age', ascending=False)
print("Sorted DataFrame:")
print(sorted_df)
print()

# Writing to CSV file
csv_file = 'data.csv'
df.to_csv(csv_file, index=False)
print("DataFrame saved to", csv_file)

## 3.1. Other key funtions in pandas

In [ ]:
import ipywidgets as widgets 
from ipywidgets import interact, interact_manual
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

### Importing and Existing Dataset
> Collaborative problem solving (CPS) Data (Polyak et al., 2017).\
> *“a sample of middle school children who interacted with a game-like, online simulation of collaborative problem-solving tasks.”*

---
#### Collaborative Problem Solving Variables

| Variable            | 
|-----------------------------|
| Feture Identification (FI)                 | 
| Maintaining a Shared Understanding (MU)                     | 
| Engagement/Interaction (EN)           | 
| Strategy (S) | 
| Evaluate (EV)             | 



In [ ]:
data_path = "https://raw.githubusercontent.com/jinnieshinufl/EDF-6938-Computational-Psychometrics/main/2022/week3_data/cps.csv"
data = pd.read_csv(data_path, header=None) #designate the path to the dataset 

data.columns = ['FI', 'MU', 'EN', 'S', 'EV']
data.describe()

FI          MU          EN           S          EV
count  159.000000  159.000000  159.000000  159.000000  159.000000
mean    25.320755   17.276730   32.635220    3.207547    3.000000
std     18.491298   10.524782   21.486358    2.128991    3.603795
min      0.000000    0.000000    0.000000    0.000000    0.000000
25%      6.000000    9.000000   14.500000    2.000000    0.000000
50%     28.000000   17.000000   31.000000    3.000000    2.000000
75%     42.000000   24.000000   50.000000    5.000000    4.500000
max     60.000000   43.000000   79.000000    9.000000   15.000000

In [ ]:
data.columns # we just used pd.read_excel() in order to upload your dataset 

In [ ]:
data.index # index number 

> Dimension of the dataframe can be simply checked using ```len()``` or ```.shape()```

In [ ]:
data.shape # without the .()

### Subselecting or Slicing a dataframe <a class="anchor" id="matrix"></a>

> Subselecting and extracting rows based on row numbers ```data.iloc[index]```

In [ ]:
start_row = 0
finish_row = 10
data.iloc[start_row:finish_row] # Extract row 0 to row 10

FI  MU  EN  S  EV
0  47  10  26  3   7
1  39  21  31  4   9
2  43  31  77  4   3
3  55  41  67  2   0
4   2   0   0  0   0
5  48  32  63  4  11
6  28  14  30  5   0
7  44  35  60  7   4
8  38  17  35  2   0
9  47  43  73  6   2

> subselecting a row using index (i.e. ID) ```data.loc[index]```

In [ ]:
row_index = 7
df.loc[row_index] # Extract row with the ID 9

### Applying a ```function``` directly to the dataframe
> We will create a function using the numpy package that will manipulate the values in a dataframe column.
    
    > dataframe[column].apply(function)
    > dataframe[column].apply(lambda x: function(x))

> First we will create a ```function``` called ```even_score```

In [ ]:
def even_score(integer): 
  if (integer % 2) == 0:
    return 'Yes'
  else:
    return 'No' #what does this function do? 

even_score(42)


'Yes'

In [ ]:
#Let's apply this function to the column `FI`


<img src="https://i.pinimg.com/736x/2e/aa/7d/2eaa7d5021ca7c3c98bc93b98b9646fe.jpg" align="left" width="70" height="70" align="left">


### Task 1: Define a function and apply it to a dataframe
> Q1: Let's define another function (`last_digit`) that outputs the last digit of the of the students' engagment score (`EN`) \

In [ ]:
################### Your Code Here ############################
#Q1 - Part 1 ANSWER 
def last_digit(input):
    
    
    return 
###############################################################

# Apply your function to the right column 

################### Your Code Here ############################
#Q1 - Part 2 ANSWER 


###############################################################

*Preliminary* Descriptive Analysis with `Pandas`

> Basic descriptive statistics using `data.max()`, `data.min()`, `data.mean()`, `data.mode()`

> Correlation Analysis using `data.corr()`

In [ ]:
print(data.max())

FI    60
MU    43
EN    79
S      9
EV    15
dtype: int64


In [ ]:
print(data.min())

FI    0
MU    0
EN    0
S     0
EV    0
dtype: int64


> `data.describe()` for a short-cut

In [ ]:
data.describe()

FI          MU          EN           S          EV
count  159.000000  159.000000  159.000000  159.000000  159.000000
mean    25.320755   17.276730   32.635220    3.207547    3.000000
std     18.491298   10.524782   21.486358    2.128991    3.603795
min      0.000000    0.000000    0.000000    0.000000    0.000000
25%      6.000000    9.000000   14.500000    2.000000    0.000000
50%     28.000000   17.000000   31.000000    3.000000    2.000000
75%     42.000000   24.000000   50.000000    5.000000    4.500000
max     60.000000   43.000000   79.000000    9.000000   15.000000

In [ ]:
# What if I want to evaluate the maximum and minimum scores of the student across the different categories?
print(data.max(axis=1))

# What if I want to evaluate the maximum and minimum scores of the student across the different categories?
print(data.min(axis=1))


0      47
1      39
2      77
3      67
4       2
       ..
154    14
155    39
156     7
157    17
158     9
Length: 159, dtype: int64

0      3
1      4
2      3
3      0
4      0
      ..
154    1
155    1
156    0
157    1
158    0
Length: 159, dtype: int64

In [ ]:
data.corr()

FI        MU        EN         S        EV
FI  1.000000  0.784238  0.881299  0.586712  0.576221
MU  0.784238  1.000000  0.900477  0.635214  0.539647
EN  0.881299  0.900477  1.000000  0.657209  0.546822
S   0.586712  0.635214  0.657209  1.000000  0.611262
EV  0.576221  0.539647  0.546822  0.611262  1.000000